//! # SlotMap Implementation
//!
//! A data structure that returns unique, stable keys (generational indices) when elements are inserted,
//! allowing O(1) retrieval and deletion while completely solving the ABA problem safely.
//!
//! **Replaces Crates:** `slotmap`, `generational-arena`
//!
//! **Real-world Usage:**
//! - Game Engines (ECS entity storage where entities die but IDs shouldn't be reused immediately for old references).
//! - Graph data structures (storing nodes and edges safely without `Rc<RefCell<T>>`).
//! - UI frameworks (tracking widgets).
//!
//! **Why build it yourself?**
//! Building a SlotMap teaches you how generational indices work. It's the standard solution to "I need references
//! to things in a collection, but I also need to mutate the collection" in Rust. By keeping a generation counter
//! alongside the data, you can catch dangling index bugs at runtime with zero unsafe code.

// =========================================================================================
// Architecture
// =========================================================================================
//
// Data Structure:
//
//      Key (Index, Generation)
//
//      SlotMap
//      ├── free_head: Option<usize> (Points to the first free slot)
//      └── slots: Vec<Slot<T>>
//                  ├── Occupied(value, generation)
//                  └── Free(next_free_index, generation)
//
// Invariants:
// 1. Every slot has a `generation` counter that increments every time the slot is freed.
// 2. A returned `Key` contains both the index and the generation at the time of insertion.
// 3. When accessing by `Key`, the generation in the key must match the generation in the slot.
// 4. `free_head` forms a singly-linked free list through the `Free` slots.
//
// Complexity:
// ┌───────────┬────────┬────────┐
// │ Operation │ Time   │ Space  │
// ├───────────┼────────┼────────┤
// │ insert    │ O(1)*  │ O(1)   │
// │ remove    │ O(1)   │ O(1)   │
// │ get       │ O(1)   │ O(1)   │
// └───────────┴────────┴────────┘
// * Amortized O(1) due to Vec reallocation if capacity is exceeded.
//
// Design Decisions:
// - **Generations**: We use `u32` for generations. If a slot is reused 4 billion times, the generation
//   could overflow and ABA could theoretically occur. Real crates often handle overflow by never
//   reusing the slot again or using `u64`.
// - **Free List**: We thread the free list directly through the empty slots using the enum variant,
//   avoiding external free-list allocations.

use std::mem;

/// A key generated by the `SlotMap` to uniquely identify an inserted element.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Key {
    index: usize,
    generation: u32,
}

impl Key {
    // Expose index and generation for potential external use or debugging, though typically opaque.
    pub fn index(&self) -> usize {
        self.index
    }
    pub fn generation(&self) -> u32 {
        self.generation
    }
}

/// The state of a single slot in the underlying vector.
enum Slot<T> {
    Occupied {
        value: T,
        generation: u32,
    },
    Free {
        next_free: Option<usize>,
        generation: u32,
    },
}

/// A generational arena that provides stable O(1) insertion, deletion, and lookup.
pub struct SlotMap<T> {
    slots: Vec<Slot<T>>,
    free_head: Option<usize>,
    len: usize,
}

impl<T> SlotMap<T> {
    /// Creates a new, empty `SlotMap`.
    #[must_use]
    pub fn new() -> Self {
        Self {
            slots: Vec::new(),
            free_head: None,
            len: 0,
        }
    }

    /// Creates a new `SlotMap` with the specified capacity.
    #[must_use]
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            slots: Vec::with_capacity(capacity),
            free_head: None,
            len: 0,
        }
    }

    /// Returns the number of elements in the map.
    #[must_use]
    pub fn len(&self) -> usize {
        self.len
    }

    /// Returns `true` if the map contains no elements.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Inserts a value into the map, returning a unique `Key`.
    pub fn insert(&mut self, value: T) -> Key {
        self.len += 1;

        if let Some(index) = self.free_head {
            // RUST INSIGHT:
            // We use pattern matching to safely extract the next free node's index
            // and the slot's generation, ensuring we update the free list correctly.
            if let Slot::Free { next_free, generation } = self.slots[index] {
                self.free_head = next_free;
                self.slots[index] = Slot::Occupied {
                    value,
                    generation,
                };
                Key { index, generation }
            } else {
                unreachable!("free_head pointed to an Occupied slot");
            }
        } else {
            // No free slots, push a new one.
            let index = self.slots.len();
            let generation = 1; // Generation starts at 1
            self.slots.push(Slot::Occupied { value, generation });
            Key { index, generation }
        }
    }

    /// Removes a value from the map by its key.
    /// Returns `Some(value)` if the key was valid, or `None` if invalid or already removed.
    pub fn remove(&mut self, key: Key) -> Option<T> {
        if let Some(slot) = self.slots.get_mut(key.index) {
            match slot {
                Slot::Occupied { generation, .. } if *generation == key.generation => {
                    // GOTCHA:
                    // We must temporarily replace the slot to move the value out.
                    // We use std::mem::replace to put a dummy Free slot in its place temporarily,
                    // or just swap it with the constructed Free slot directly.
                    let current_gen = *generation;
                    let next_gen = current_gen.wrapping_add(1); // Handle overflow safely (though theoretically causes ABA if it wraps exactly)

                    let new_slot = Slot::Free {
                        next_free: self.free_head,
                        generation: next_gen,
                    };

                    // Replace the occupied slot with the new free slot, extracting the old one.
                    let old_slot = mem::replace(slot, new_slot);

                    if let Slot::Occupied { value, .. } = old_slot {
                        self.free_head = Some(key.index);
                        self.len -= 1;
                        return Some(value);
                    } else {
                        unreachable!();
                    }
                }
                _ => return None, // Generation mismatch or already free (ABA prevented)
            }
        }
        None
    }

    /// Gets a reference to the value associated with the key.
    #[must_use]
    pub fn get(&self, key: Key) -> Option<&T> {
        if let Some(Slot::Occupied { value, generation }) = self.slots.get(key.index) {
            if *generation == key.generation {
                return Some(value);
            }
        }
        None
    }

    /// Gets a mutable reference to the value associated with the key.
    pub fn get_mut(&mut self, key: Key) -> Option<&mut T> {
        if let Some(Slot::Occupied { value, generation }) = self.slots.get_mut(key.index) {
            if *generation == key.generation {
                return Some(value);
            }
        }
        None
    }

    /// Retains only the elements specified by the predicate.
    pub fn retain<F>(&mut self, mut f: F)
    where
        F: FnMut(Key, &mut T) -> bool,
    {
        // We can't iterate and mutate self easily without index looping.
        for index in 0..self.slots.len() {
            let retain = if let Slot::Occupied { value, generation } = &mut self.slots[index] {
                f(Key { index, generation: *generation }, value)
            } else {
                true // Keep free slots as they are
            };

            if !retain {
                // If we need to remove, we construct the key and call remove.
                // We know it's Occupied from the check above.
                let g = match self.slots[index] {
                    Slot::Occupied { generation, .. } => generation,
                    _ => unreachable!(),
                };
                self.remove(Key { index, generation: g });
            }
        }
    }
}

impl<T> Default for SlotMap<T> {
    fn default() -> Self {
        Self::new()
    }
}

// =========================================================================================
// Tests
// =========================================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_insert_and_get() {
        let mut sm = SlotMap::new();
        let k1 = sm.insert("hello");
        let k2 = sm.insert("world");

        assert_eq!(sm.len(), 2);
        assert_eq!(sm.get(k1), Some(&"hello"));
        assert_eq!(sm.get(k2), Some(&"world"));
    }

    #[test]
    fn test_remove() {
        let mut sm = SlotMap::new();
        let k1 = sm.insert(10);

        assert_eq!(sm.remove(k1), Some(10));
        assert_eq!(sm.len(), 0);
        assert_eq!(sm.get(k1), None);

        // Double remove should fail
        assert_eq!(sm.remove(k1), None);
    }

    #[test]
    fn test_aba_prevention() {
        let mut sm = SlotMap::new();
        let k1 = sm.insert(100);
        sm.remove(k1);

        // This insert should reuse the slot of k1, but with a new generation
        let k2 = sm.insert(200);

        // The indices should be the same
        assert_eq!(k1.index, k2.index);
        // But the generations must be different
        assert_ne!(k1.generation, k2.generation);

        // Using the old key should fail
        assert_eq!(sm.get(k1), None);
        // Using the new key should succeed
        assert_eq!(sm.get(k2), Some(&200));
    }

    #[test]
    fn test_freelist_chaining() {
        let mut sm = SlotMap::new();
        let k1 = sm.insert(1);
        let k2 = sm.insert(2);
        let k3 = sm.insert(3);

        sm.remove(k2);
        sm.remove(k1);

        // free list should be k1 -> k2
        let k4 = sm.insert(4); // should take k1's old slot
        let k5 = sm.insert(5); // should take k2's old slot

        assert_eq!(k4.index, k1.index);
        assert_eq!(k5.index, k2.index);
    }

    #[test]
    fn test_retain() {
        let mut sm = SlotMap::new();
        let k1 = sm.insert(1);
        let k2 = sm.insert(2);
        let k3 = sm.insert(3);

        sm.retain(|_, val| *val % 2 != 0); // Keep odd numbers

        assert_eq!(sm.len(), 2);
        assert_eq!(sm.get(k1), Some(&1));
        assert_eq!(sm.get(k2), None);
        assert_eq!(sm.get(k3), Some(&3));
    }
}

// =========================================================================================
// Footer
// =========================================================================================
// Comparison to `slotmap`:
// The actual `slotmap` crate has much more advanced features:
// - Specialized key types (macros to generate newtype wrappers around keys so you don't mix up keys
//   from different maps).
// - Secondary maps (maps that use keys from a primary map, but don't manage the generations themselves).
// - DenseSlotMap implementation (keeps values densely packed for iteration performance while keeping
//   sparse generational indices).
//
// What's missing:
// - Iterators (`iter()`, `iter_mut()`, `drain()`).
// - Protection against generation wrapping (e.g., stopping slot reuse if generation hits u32::MAX).
// - Newtype key generation.
//
// Next steps:
// - Implement a `DenseSlotMap` variant that stores values in a packed `Vec` and uses the `slots`
//   array purely as an indirection table, allowing cache-friendly iteration over all values.