//! # Async Runtime
//!
//! This implements a minimal asynchronous runtime, replacing crates like `tokio` and `async-std`.
//!
//! Real-world systems that use this:
//! - Web servers handling thousands of concurrent connections (e.g., hyper, actix-web)
//! - Database drivers doing asynchronous I/O
//! - Networked applications multiplexing many streams over a single thread or a thread pool
//!
//! Why build it yourself?
//! - To demystify the "black magic" of `async`/`.await` in Rust.
//! - To understand exactly what `Waker`, `Context`, and `Future` do under the hood.
//! - To learn how an executor schedules tasks and how a reactor wakes them up.
//!
//! ## Architecture
//!
//! - **Future**: A state machine generated by the compiler when using `async`. It has a `poll` method.
//! - **Task**: A wrapper around a Future that pins it to a specific memory location and provides waking capabilities.
//! - **Executor**: A scheduler that pulls tasks from a queue (e.g., a channel) and polls them. If a task returns `Poll::Pending`, the executor stops working on it.
//! - **Reactor**: A system component (in our case, a `TimerReactor`) that waits for external events (like time passing or I/O) and then signals the executor to wake up a specific task.
//! - **Waker**: A callback mechanism that the reactor uses to tell the executor a task is ready to be polled again.
//!
//! ## Time/Space Complexity (Executor Loop)
//! - Time: O(1) per task poll (excluding the future's actual work)
//! - Space: O(N) where N is the number of active tasks in the queue.

//! ## Benchmarking
//! To benchmark this runtime, one would use `criterion` to measure task spawning overhead
//! and polling latency:
//! ```rust,ignore
//! c.bench_function("spawn_10k_tasks", |b| b.iter(|| {
//!     let (exec, spawner) = new_executor_and_spawner();
//!     for _ in 0..10_000 {
//!         spawner.spawn(async { std::hint::black_box(1 + 1); });
//!     }
//!     drop(spawner);
//!     exec.run();
//! }));
//! ```
//!
//! ## Footer
//! - **How this compares**: Canonical crates like `tokio` use work-stealing multi-threaded executors and `epoll`/`kqueue` / `io_uring` for highly efficient, non-blocking I/O and timers.
//! - **What is missing**: Multi-threading, task cancellation, CPU pinning, complex I/O polling (like sockets).
//! - **Next steps**: Implement a socket reactor using `mio` to support asynchronous TCP streams, and convert the executor to a multi-threaded work-stealing pool using `crossbeam-deque`.

use std::{
    collections::BTreeMap,
    future::Future,
    pin::Pin,
    sync::atomic::AtomicUsize,
    sync::{
        Arc, Mutex, OnceLock,
        atomic::{AtomicBool, Ordering},
        mpsc::{Receiver, SyncSender, sync_channel},
    },
    task::{Context, Poll, Wake, Waker},
    thread,
    time::{Duration, Instant},
};

/// Trait defining an executor that can run tasks to completion.
pub trait AsyncExecutor {
    /// Runs the executor loop until no more tasks remain or the executor shuts down.
    fn run(&self);
}

/// Trait defining a spawner that can spawn new async tasks onto the executor.
pub trait AsyncSpawner {
    /// Spawns a new future onto the executor.
    fn spawn(&self, future: impl Future<Output = ()> + 'static + Send);
}

/// A wrapper around a dynamically dispatched future.
type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// A task representing a spawned future. It implements `Wake` to allow the executor
/// to re-poll it when notified by a reactor.
struct Task {
    /// The actual future being executed. Pin is required for self-referential futures.
    // RUST INSIGHT: `Pin<Box<...>>` guarantees the future won't move in memory, which is essential
    // for `async` blocks since they can contain self-referential local variables.
    future: Mutex<Option<BoxFuture<'static, ()>>>,
    /// Channel to send the task back to the executor when it wakes up.
    task_sender: SyncSender<Arc<Self>>,
}

impl Wake for Task {
    fn wake(self: Arc<Self>) {
        self.wake_by_ref();
    }

    fn wake_by_ref(self: &Arc<Self>) {
        // RUST INSIGHT: `wake` sends a clone of `Arc<Task>` into the channel.
        // This is safe and non-blocking because we use a SyncSender, but we must
        // handle the `Err` case gracefully if the executor has shut down.
        // We use `try_send` to avoid blocking the reactor thread if the channel is full.
        let _ = self.task_sender.try_send(self.clone());
    }
}

/// Our minimal executor, wrapping a task receiver.
pub struct MiniExecutor {
    ready_queue: Receiver<Arc<Task>>,
}

impl AsyncExecutor for MiniExecutor {
    fn run(&self) {
        // GOTCHA: We loop while we can receive tasks. If the channel is disconnected
        // (all spawners dropped), `recv()` returns an error, and the loop naturally terminates.
        while let Ok(task) = self.ready_queue.recv() {
            let mut future_slot = task.future.lock().unwrap();
            if let Some(mut future) = future_slot.take() {
                // RUST INSIGHT: We construct a Waker from the `Arc<Task>`.
                // `Waker::from_wake` requires the type to implement `Wake`.
                let waker = Waker::from(task.clone());
                let mut context = Context::from_waker(&waker);

                // PRODUCTION NOTE: A real executor (like tokio) uses a much more complex
                // state machine and potentially work-stealing across multiple threads.
                // We use a simple single-threaded loop pulling from an MPSC channel.
                match future.as_mut().poll(&mut context) {
                    Poll::Pending => {
                        // The future is not ready. Put it back in the task.
                        // We do NOT send it back to the channel here. The reactor
                        // will call `waker.wake()` to send it back when ready.
                        *future_slot = Some(future);
                    }
                    Poll::Ready(()) => {
                        // The future completed. We just let it drop.
                    }
                }
            }
        }
    }
}

#[derive(Clone)]
pub struct MiniSpawner {
    task_sender: SyncSender<Arc<Task>>,
}

impl AsyncSpawner for MiniSpawner {
    fn spawn(&self, future: impl Future<Output = ()> + 'static + Send) {
        let future = Box::pin(future);
        let task = Arc::new(Task {
            future: Mutex::new(Some(future)),
            task_sender: self.task_sender.clone(),
        });

        // Push the initial task onto the queue to be polled for the first time.
        self.task_sender.send(task).expect("too many tasks queued");
    }
}

/// Creates a new executor and spawner pair.
#[must_use]
pub fn new_executor_and_spawner() -> (MiniExecutor, MiniSpawner) {
    // 10,000 max queued tasks is plenty for this minimal runtime.
    let (task_sender, ready_queue) = sync_channel(10_000);
    (MiniExecutor { ready_queue }, MiniSpawner { task_sender })
}

// -----------------------------------------------------------------------------
// Reactor and Timers
// -----------------------------------------------------------------------------

/// State for a single sleep timer.
struct TimerState {
    completed: bool,
    waker: Option<Waker>,
}

/// A global timer reactor that tracks sleeping futures.
pub struct TimerReactor {
    // BTreeMap keeps timers sorted by expiration time.
    #[allow(clippy::type_complexity)]
    timers: Mutex<BTreeMap<(Instant, usize), Arc<Mutex<TimerState>>>>,
    shutdown: AtomicBool,
    next_id: AtomicUsize,
}

impl TimerReactor {
    const fn new() -> Self {
        Self {
            timers: Mutex::new(BTreeMap::new()),
            next_id: AtomicUsize::new(0),
            shutdown: AtomicBool::new(false),
        }
    }

    /// The reactor thread loop.
    fn run(&self) {
        while !self.shutdown.load(Ordering::Relaxed) {
            let now = Instant::now();
            let mut timers_to_wake = Vec::new();

            {
                let mut timers = self.timers.lock().unwrap();
                // Split off the timers that are still in the future.
                // The remaining timers in `expired` are <= `now`.
                // BTreeMap::split_off returns keys >= the given key.
                let mut unexpired = timers.split_off(&(now + Duration::from_nanos(1), 0));

                // Swap unexpired back into `timers`, leaving expired timers in `timers` temporarily,
                // then swap them. A more efficient way is:
                std::mem::swap(&mut *timers, &mut unexpired);
                drop(timers);
                let expired = unexpired;

                for (_instant, state) in expired {
                    timers_to_wake.push(state);
                }
            }

            for state_mutex in timers_to_wake {
                let mut state = state_mutex.lock().unwrap();
                state.completed = true;
                if let Some(waker) = state.waker.take() {
                    waker.wake();
                }
            }

            // Sleep a tiny bit to prevent 100% CPU usage.
            // PRODUCTION NOTE: Real reactors use `epoll`/`kqueue`/`IOCP` with a timeout,
            // so they block exactly until the next timer expires or I/O occurs, avoiding spin-waiting.
            thread::sleep(Duration::from_millis(1));
        }
    }
}

// RUST INSIGHT: We use `OnceLock<&'static TimerReactor>` and `Box::leak`
// to create a global, static reference to the reactor. This avoids needing
// to pass the reactor around explicitly to every `sleep` future.
static TIMER_REACTOR: OnceLock<&'static TimerReactor> = OnceLock::new();

fn get_reactor() -> &'static TimerReactor {
    TIMER_REACTOR.get_or_init(|| {
        let reactor = Box::new(TimerReactor::new());
        let reactor_ref: &'static TimerReactor = Box::leak(reactor);

        // Spawn the reactor thread.
        thread::spawn(move || {
            reactor_ref.run();
        });

        reactor_ref
    })
}

/// A future that completes after a given duration.
pub struct Sleep {
    _expiration: Instant,
    state: Arc<Mutex<TimerState>>,
}

impl Future for Sleep {
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut state = self.state.lock().unwrap();

        if state.completed {
            Poll::Ready(())
        } else {
            // Update the waker in case it changed.
            state.waker = Some(cx.waker().clone());
            Poll::Pending
        }
    }
}

/// Suspends execution for a given duration.
///
/// # Panics
///
/// Panics if the timer reactor lock is poisoned.
#[must_use]
pub fn sleep(duration: Duration) -> Sleep {
    let reactor = get_reactor();
    let expiration = Instant::now() + duration;

    let state = Arc::new(Mutex::new(TimerState {
        completed: false,
        waker: None,
    }));

    let id = reactor.next_id.fetch_add(1, Ordering::Relaxed);
    reactor
        .timers
        .lock()
        .unwrap()
        .insert((expiration, id), state.clone());

    Sleep {
        _expiration: expiration,
        state,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    #[test]
    fn test_happy_path_async() {
        let (executor, spawner) = new_executor_and_spawner();
        let counter = Arc::new(AtomicUsize::new(0));
        let counter_clone = counter.clone();

        spawner.spawn(async move {
            counter_clone.fetch_add(1, Ordering::SeqCst);
        });

        // Drop the spawner so the executor loop terminates after finishing tasks.
        drop(spawner);
        executor.run();

        assert_eq!(counter.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn test_timer_edge_cases() {
        let (executor, spawner) = new_executor_and_spawner();
        let counter = Arc::new(AtomicUsize::new(0));

        let c1 = counter.clone();
        spawner.spawn(async move {
            sleep(Duration::from_millis(10)).await;
            c1.fetch_add(1, Ordering::SeqCst);
        });

        let c2 = counter.clone();
        spawner.spawn(async move {
            sleep(Duration::from_millis(20)).await;
            c2.fetch_add(2, Ordering::SeqCst);
        });

        drop(spawner);

        let start = Instant::now();
        executor.run();
        let elapsed = start.elapsed();

        assert_eq!(counter.load(Ordering::SeqCst), 3);
        // It should take at least 20ms, but definitely less than 100ms
        assert!(elapsed >= Duration::from_millis(15));
        assert!(elapsed < Duration::from_millis(100));
    }

    #[test]
    fn test_high_concurrency_boundaries() {
        let (executor, spawner) = new_executor_and_spawner();
        let counter = Arc::new(AtomicUsize::new(0));

        // Spawn 1000 tasks
        for _ in 0..1000 {
            let c = counter.clone();
            spawner.spawn(async move {
                // Mix immediate execution and sleeping
                c.fetch_add(1, Ordering::SeqCst);
                sleep(Duration::from_millis(5)).await;
                c.fetch_add(1, Ordering::SeqCst);
            });
        }

        drop(spawner);
        executor.run();

        assert_eq!(counter.load(Ordering::SeqCst), 2000);
    }
}
